name: DPM
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _pytorch_select=0.1
  - _tflow_select=2.1.0
  - absl-py=0.9.0
  - astor=0.8.0
  - blas=1.0
  - c-ares=1.15.0
  - ca-certificates=2020.6.24
  - certifi=2020.6.20
  - cffi=1.14.0
  - cudatoolkit=10.1.243
  - cudnn=7.6.5
  - cupti=10.1.168
  - gast=0.3.3
  - google-pasta=0.2.0
  - grpcio=1.27.2
  - h5py=2.10.0
  - hdf5=1.10.6
  - intel-openmp=2019.4
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libprotobuf=3.12.3
  - libstdcxx-ng=9.1.0
  - markdown=3.1.1
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.0
  - ncurses=6.2
  - ninja=1.9.0
  - numpy=1.18.5
  - numpy-base=1.18.5
  - openssl=1.1.1g
  - pip=20.1.1
  - protobuf=3.12.3
  - pycparser=2.20
  - python=3.7.7
  - pytorch=1.5.0
  - readline=8.0
  - scipy=1.5.0
  - setuptools=49.2.0
  - six=1.15.0
  - sqlite=3.32.3
  - tensorboard=1.14.0
  - tensorflow=1.14.0
  - tensorflow-base=1.14.0
  - tensorflow-estimator=1.14.0
  - tensorflow-gpu=1.14.0
  - termcolor=1.1.0
  - tk=8.6.10
  - werkzeug=1.0.1
  - wheel=0.34.2
  - wrapt=1.12.1
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - backcall==0.2.0
    - cycler==0.10.0
    - decorator==4.4.2
    - ipython==7.17.0
    - ipython-genutils==0.2.0
    - jedi==0.17.2
    - joblib==0.16.0
    - keras==2.4.3
    - kiwisolver==1.2.0
    - matplotlib==3.3.1
    - pandas==1.1.0
    - parso==0.7.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==7.2.0
    - plotting==0.0.7
    - prompt-toolkit==3.0.6
    - ptyprocess==0.6.0
    - pydoe==0.3.8
    - pygments==2.6.1
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pytz==2020.1
    - pyyaml==5.3.1
    - scikit-learn==0.23.2
    - seaborn==0.10.1
    - sklearn==0.0
    - threadpoolctl==2.1.0
    - traitlets==4.3.3
    - wcwidth==0.2.5